site_name: Manish writes about it...
site_url: https://savvystrider.github.io

nav:
    - 'Home': 'index.md'
    - 'About': 'about.md'
    - 'APIs':
        - 'What are APIs?': 'what-is-an-api.md'
        - 'API vocabulary': 'api-vocabulary.md'
    - 'REST APIs':
        - 'What are REST APIs?': 'what-is-a-rest-api.md'
        - 'What is REST?': 'what-is-rest.md'
        - 'Five common sections in REST API documents': 'five-common-sections-in-rest-api-docs.md'
        - 'What is an endpoint?': 'what-is-an-endpoint.md'
        - 'What is Postman?': 'what-is-postman.md'
        - 'REST API vocabulary': 'rest-api-vocabulary.md'
    - 'HTTP':
           - 'What is HTTP?': 'what-is-http.md'
           - 'What are HTTP methods?': 'what-are-http-methods.md'
           - 'What are HTTP messages?': 'what-are-http-messages.md'
           - 'What are HTTP requests?': 'what-are-http-requests.md'
           - 'What are HTTP responses?': 'what-are-http-responses.md'
           - 'The syntax of URIs': 'the-syntax-of-uris.md'
           - 'HTTP vocabulary': 'http-vocabulary.md'
    - 'JSON':
           - 'What is JSON?': 'what-is-json.md'
           - 'What are the basic JSON data types?': 'what-are-basic-json-data-types.md'
           - 'What are arrays and objects?': 'what-are-arrays-and-objects-in-json.md'
           - 'What is nesting?': 'what-is-nesting-in-json.md'
           - 'Documenting a single-level response in JSON': 'documenting-single-level-response-in-json.md'
           - 'Documenting JSON with nesting': 'documenting-json-with-nesting.md'
           - 'Documenting JSON requests': 'documenting-json-requests.md'
           - 'Activity - Using JSON to describe the structure of a menu': 'activity-using-json-to-describe-menu-structure.md'
           - 'JSON vocabulary': 'json-vocabulary.md'
    - 'curl':
        - 'What is curl?': 'what-is-curl.md'
        - 'curl command options': 'what-are-curl-command-options.md'
        - 'Activity - Use methods with curl': 'activity-use-methods-with-curl.md'
    - 'Exercise - Documenting Endpoints':
        - 'Exercise - Documenting API endpoints': 'exercise-documenting-api-endpoints.md'
        - 'Mock surf report wiki': 'mock-surf-report-wiki.md'
        - 'Mock surf report API documentation': 'mock-surf-report-api-documentation.md'                                                     
    - 'XML':
        - 'What is XML?': 'what-is-xml.md'
        - 'What are tags and elements in XML?': 'what-are-tags-and-elements-in-xml.md'
        - 'What are attributes in XML?': 'what-are-attributes-in-xml.md'
        - 'What are namespaces in XML?': 'what-are-namespaces-in-xml.md'
        - 'Using XML to document a weather forecast': 'using-xml-to-document-weather-forecast.md'
        - 'Using XML to document a request to record a TV program': 'using-xml-to-document-request-to-record-TV-program.md'
        - 'XML vocabulary': 'xml-vocabulary.md'
    - 'Git':
        - 'What is Git?': 'what-is-git.md'
        - 'How do I configure Git?': 'how-to-configure-git.md'
        - 'How do I initialize a Git repository?': 'how-to-initialize-git-repository.md'
        - 'What is the architecture of Git?': 'what-is-git-architecture.md'
        - 'How do I add files in Git?': 'how-to-add-files-in-git.md'
        - 'How do I commit changes in Git?': 'how-to-commit-changes-in-git.md'
        - 'Git vocabulary': 'git-vocabulary.md'    
theme: material
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format