site_name: Manish writes about it...
site_url: https://savvystrider.github.io

nav:
    - 'Home': 'index.md'
    - 'About': 'about.md'
    - 'APIs':
        - 'What are APIs?': 'what-is-an-api.md'
        - 'API vocabulary': 'api-vocabulary.md'
    - 'REST APIs':
        - 'What are REST APIs?': 'what-is-a-rest-api.md'
        - 'What is REST?': 'what-is-rest.md'
        - 'Five common sections in REST API documents': 'five-common-sections-in-rest-api-docs.md'
        - 'What is an endpoint?': 'what-is-an-endpoint.md'
        - 'What is Postman?': 'what-is-postman.md'
        - 'REST API vocabulary': 'rest-api-vocabulary.md'
    - 'HTTP':
           - 'What is HTTP?': 'what-is-http.md'
           - 'What are HTTP methods?': 'what-are-http-methods.md'
           - 'What are HTTP messages?': 'what-are-http-messages.md'
           - 'What are HTTP requests?': 'what-are-http-requests.md'
           - 'What are HTTP responses?': 'what-are-http-responses.md'
           - 'The syntax of URIs': 'the-syntax-of-uris.md'                        

theme: material
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format